springdoc.swagger-ui.urls[0].name=Cosmo Cats Product API
springdoc.swagger-ui.urls[0].url=/cosmo-cats-product-api.yml
supplier.base-url=http://localhost:8089
spring.application.name=lab1

# API versioning
api.prefix=/api/v1.2

# Feature toggles
feature.cosmoCats.enabled=true
feature.kittyProducts.enabled=false

# Database configuration
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/cosmocats}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA configuration
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Liquibase configuration
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.yaml

# OAuth2 Resource Server (JWT)
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8089
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=http://localhost:8089/.well-known/jwks.json
